name: Call API on Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call API
        run: |
          curl -X POST https://food-delivery-web-pvcg.onrender.com/ \
          -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"key": "value"}'
